openapi: 3.0.0
info:
  title: Bitcoin Address Generation API
  version: 1.0.0
  description: An API to generate mnemonic seeds and various types of Bitcoin addresses.
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /generate-mnemonic:
    post:
      summary: Generate a mnemonic seed phrase
      description: Generates a BIP39 compliant mnemonic seed phrase.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numWords:
                  type: integer
                  default: 24
                  description: Number of words in the mnemonic seed.
              example:
                numWords: 24
      responses:
        "200":
          description: Mnemonic seed generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  mnemonic:
                    type: string
                    description: The generated mnemonic seed phrase.
  /generate-address:
    post:
      summary: Generate a Bitcoin address based on type
      description: Generates a Bitcoin address based on the provided type, mnemonic, and additional parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - mnemonic
              properties:
                type:
                  type: string
                  enum: [bip44, bip49, bip84, bip86, brainwallet]
                  description: The type of Bitcoin address to generate.
                mnemonic:
                  type: string
                  description: Mnemonic seed phrase for address derivation.
                passphrase:
                  type: string
                  description: Optional passphrase for additional security.
                index:
                  type: integer
                  default: 0
                  description: Derivation index for hierarchical deterministic wallets.
              example:
                type: bip44
                mnemonic: "example mnemonic here"
                passphrase: "secure passphrase"
                index: 0
      responses:
        "200":
          description: Address generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    description: Generated Bitcoin address.
                  public_key:
                    type: string
                    description: Public key associated with the address (for BIP types).
        "400":
          description: Bad request - invalid input parameters
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
